{% set name = "slackclient" %}
{% set version = "2.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 839f9c0bf5564c8e137fd63ae79d1a510ab2abde2eeb108fc23d28616069c2bb

build:
  number: 0
  skip: true  # [py<=35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - aiohttp >3.5.2
    - aiodns >1.0

test:
  imports:
    - slack

about:
  home: https://github.com/slackhq/python-slackclient
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client for Slack.com
  doc_url: https://slackapi.github.io/python-slackclient/
  dev_url: https://github.com/slackhq/python-slackclient

extra:
  recipe-maintainers:
    - pmlandwehr
    - CurtLH
