{%set name = "slackclient" %}
{%set version = "1.0.5" %}
{%set hash_type = "sha256" %}
{%set hash_val = "32895b7ec271b60d02e6cdd03afa3797bcde649ce520a70965db414390607995" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - websocket-client
    - requests
    - six

test:
  imports:
    - slackclient

about:
  home: http://github.com/slackhq/python-slackclient
  license: MIT
  license_file: LICENSE
  summary: 'Python client for Slack.com'

extra:
  recipe-maintainers:
    - pmlandwehr
