{% set name = "slackclient" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f9da5b111b8c4944380674d193c3ffd5bd4a36cda8b58fb2404f900afb0b1fa

build:
  number: 1
  noarch: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - aiohttp >3.5.2
    - aiodns >1.0

test:
  imports:
    - slack

about:
  home: https://github.com/slackhq/python-slackclient
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python client for Slack.com'
  doc_url: https://slackapi.github.io/python-slackclient/
  dev_url: https://github.com/slackhq/python-slackclient

extra:
  recipe-maintainers:
    - pmlandwehr
    - CurtLH
