# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "G0cqTxgs/qduDYFD5ScQ/gVrZTvWQAocG7j25K24Qpe8hYbrIKNjq3Kud2nRXpqb/AF6xR8I5sX0WtEp4MnFpCzBAnnA1QrF3CSWTFvGJXhy6EDURvGpFF3Ad56JKzr7yq9OmaF5oOVgRkX8DV78SdYaJfiI3x+TRnc5t0j13POh3DHwxRE7h2Rz7KZifEaOhNQnGBIDSQ8ZqmeWBkI2jn8bGltcJb59cg7EIduhp7q1QA7ZAKTu/7KWMR5ctKM6q7TUbATNb+VvuJMu6djttYhL9IJBheSmCSyd5KjHtMgyUrYzK/qYr+0w4fUKOuBRQheRXrACYRzw6U9yTksCd3hr9hVdmTBEbQ+8TohdbktKE9lbhiutKSbXYBB3GtdvTc0KqkFhtBlkuUHRu9dtv4ehwIR6GW86BdnLQECPvpX7G210ljnYaGDz/aUygKFGxHdXL1QM3AILUGgoLY+1wYmR5bnObH62bNtKwQk52oVChlk/kZEpGvk64L6o+BWvmxvGynI/cEnVRsKvrILbLGIG5FPy65xfe7sPH7Vj0GpdrDndkdztrHHzkaajInirvHdKCnnGu5eTZ/pdMoxegunlE2mDZKiCfw7yWSf3Hqp+Og2FTepogfMOyBX6FqBGf2mgHkyi0rKxp7MkA0PGnurFwulZw0kpm4jYTlNL5+8="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
