travis:
  secure:
    BINSTAR_TOKEN: L7irdyv97HEGgyp86y5jWS/GbVjTmkd5xUdpRMpJEkXjXRRvimYGqgYe1t6k2euOLCVEmA5IqH4WrpPTPRGQqwxESXoJSKo3VO2ACsceNgL3o2jnDuyKXCqVV5YC5VY1azn+4czqEc6HTq65UawtElP4wT5NZKcAbFmdqjkaNngbGMBMxARVvyYOnu+zJhmtEfUct7lSzLallvicGQamKTXDYoltUj1KtlyrirEm1kExA4eldXK3BO8ldbPEQyQRxn++zXqfX2jZpG20jLOR1yQLDmuDNOIS374qFkh6nktAG5EtuX2ZhGe6KaMgNoTNXtdS28s5vb7S2mgKV+MZCoblpITaf07J+auRbMo39hTSY8CxrJQ7Uf51HLCahKkVNJCUyFXmI1CDM2V0O3F/+djxlkOlM0bDb5M0CtZXNZ/Si91jJd5unItG3raaDo8Phe+bPMKLpsbZ2wnsNgxLT7Y6udclGWBWXanVrOYGiHb9RI4mjkBtbPXvKcqJ/ixtfruYF7b5sO6cmcoWoP014JOCzl8eL/G85DUGl9LsP6Yj20O2AdjrkKRrvADAKFjjwL0s4Q4McQyaaMyq9tgO9FQE0GdWUMMqIclhVuFXusIXnPV6J630Aeh30gIdxcP0u3V69xhZgVBWmw4jF0C7QmQpXIddGAJ3GkdR1EbCe+s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
