travis:
  secure:
    BINSTAR_TOKEN: Cag54Z0zXJdSjPlIKtGAlsUODxmcb6MPMDfibfLQygiqW/X5RFuZcox+68rt5e8075c13otTKGrbbO1HiCtyVgrSiX+VikeBYpeWwhrCJ9VygR5NQcRcKVRYxGdGx9daHbjOuagqRgLk+pKTzrCUnNyPbepuea/0fsK2Z6WjTJNqjt9jDhKCmQyp3LyBdIhSjkid0GnhpYbUMn102KBcJEmIGQmlb/f2SgZ2Wyga/v2po75qF7gTfqm45MsWZzOp/ZHCQ9tkbx+XSNsSn2GK9ScLilb9juc3v5UCrLvvF6NSe0CTeJIsEfNs/OITZ3IiG0F+4qB9U78d7M00RmxmY5KGnccZytuYMoCLPhiVge5oRx29uRnfABOG9O4sq+TdBlgGot3YksX7VkmvUpZBcJE4YZ+1SvGBj6X+oazVveVrfUcu10ZS5ejsGp3X1nWUdT9gQkv2b3t6ocyShKHh+Fl4iQzcw6B24ziid0Y+P70xLv8Hd+3cHLfV0EG317DziTOuJfwQiw1NIlWArxXN4m7AumlJm6ZRAQX+Ju+NvCWTJeWfJWrMTf8rPPhNZrik2JrUTbhFj+/MGUJ3e1soCziRzPvzXCyjHI49hfCqzZfElmwwSKmuhIa4/0YBGh0gigbFzAqqNq6I7V8coR6kp3/iZ413ycJEfqFiAPLvt1c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
