travis:
  secure:
    BINSTAR_TOKEN: G0cqTxgs/qduDYFD5ScQ/gVrZTvWQAocG7j25K24Qpe8hYbrIKNjq3Kud2nRXpqb/AF6xR8I5sX0WtEp4MnFpCzBAnnA1QrF3CSWTFvGJXhy6EDURvGpFF3Ad56JKzr7yq9OmaF5oOVgRkX8DV78SdYaJfiI3x+TRnc5t0j13POh3DHwxRE7h2Rz7KZifEaOhNQnGBIDSQ8ZqmeWBkI2jn8bGltcJb59cg7EIduhp7q1QA7ZAKTu/7KWMR5ctKM6q7TUbATNb+VvuJMu6djttYhL9IJBheSmCSyd5KjHtMgyUrYzK/qYr+0w4fUKOuBRQheRXrACYRzw6U9yTksCd3hr9hVdmTBEbQ+8TohdbktKE9lbhiutKSbXYBB3GtdvTc0KqkFhtBlkuUHRu9dtv4ehwIR6GW86BdnLQECPvpX7G210ljnYaGDz/aUygKFGxHdXL1QM3AILUGgoLY+1wYmR5bnObH62bNtKwQk52oVChlk/kZEpGvk64L6o+BWvmxvGynI/cEnVRsKvrILbLGIG5FPy65xfe7sPH7Vj0GpdrDndkdztrHHzkaajInirvHdKCnnGu5eTZ/pdMoxegunlE2mDZKiCfw7yWSf3Hqp+Og2FTepogfMOyBX6FqBGf2mgHkyi0rKxp7MkA0PGnurFwulZw0kpm4jYTlNL5+8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
